//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Human
    {
        public int ID_Human { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string Middle_name { get; set; }
        public int Book_ID { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
