//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheque
    {
        public int ID_Cheque { get; set; }
        public int Purchase_ID { get; set; }
        public int Book_ID { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}
