//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr5
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginPassword
    {
        public int ID_LogPas { get; set; }
        public string UserLogin { get; set; }
        public string UserPassword { get; set; }
        public int Users_ID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
